spring.application.name=AgroPro

spring.datasource.url=jdbc:postgresql://localhost:5432/agropro
spring.datasource.driver-class-name=org.postgresql.Driver

# liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml

# minio
minio.url=http://127.0.0.1:9000
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=reports

# jxls
logging.level.org.jxls=DEBUG
logging.level.org.jxls.util=DEBUG

# actuator
management.endpoints.web.exposure.include=health, info, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# prometheus
management.endpoint.prometheus.access=read_only
management.prometheus.metrics.export.enabled=true
management.prometheus.metrics.export.step=15s