input {
  beats {
    port => 5044
    ssl_enabled => false
  }
}

filter {
  mutate {
    convert => {
      "httpStatus" => "integer"
      "responseTime" => "integer"
    }
    add_field => {
      "pipeline" => "agropro-logs"
    }
  }

}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS}"]
    user => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"

    index => "agropro-logs-%{+YYYY.MM.dd}"

    data_stream => false
  }

}